"""Seed catalogues for the three demo merchants.

Each list of dicts is fed directly to ``StubShopifyTransport(seed_products=[...])``.
The fields match Shopify-MCP-style shape (id, title, vendor, available, etc.)
and the adapter normalises them to UCP-vocabulary ``ProductResult`` on the way out.

Catalogue design satisfies the diversity checklist from the plan:
  - ≤ $30  (soft gate)         → Coffee Bar mugs ($14, $18)
  - $100-$500 (explicit gate)  → Athletic Co shoes, Audio Hub mid-tier
  - > $500 (full summary)      → Audio Hub Premium ($649)
  - OUT_OF_STOCK risk flag     → Trail Runner Pro at Athletic Co
  - Cross-merchant overlap     → "wireless earbuds" appears at Audio Hub
                                  AND a "athletic earbuds" at Athletic Co
"""

from __future__ import annotations


# Every image URL is globally unique across the entire catalogue.
# Uses images.unsplash.com/photo-{id} direct CDN format.
ATHLETIC_CO = [
    {
        "id": "ath_001",
        "title": "Demo Running Shoes",
        "price": "129.99",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": True,
        "rating": 4.5,
        "review_count": 240,
        "description": "Lightweight road running shoes. Cushioned midsole.",
        "attributes": {"category": "running", "type": "shoes"},
        "images": [
            "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
            "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
        ],
    },
    {
        "id": "ath_002",
        "title": "Trail Runner Pro",
        "price": "189.00",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": False,
        "rating": 4.7,
        "review_count": 142,
        "description": "Aggressive lugs, waterproof upper. Currently sold out.",
        "attributes": {"category": "running", "type": "shoes"},
        "images": [
            "https://images.unsplash.com/photo-1582898967731-b5834427fd66?w=800&q=80",
            "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80",
        ],
    },
    {
        "id": "ath_003",
        "title": "Performance Running Shorts",
        "price": "39.00",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": True,
        "rating": 4.3,
        "review_count": 88,
        "description": "Moisture-wicking. Built-in liner.",
        "attributes": {"category": "running", "type": "apparel"},
        "images": [
            "https://images.unsplash.com/photo-1602190420103-683df5093e86?w=800&q=80",
            "https://images.unsplash.com/photo-1539794830467-1f1755804d13?w=800&q=80",
        ],
    },
    {
        "id": "ath_004",
        "title": "Lightweight Training T-Shirt",
        "price": "24.99",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": True,
        "rating": 4.2,
        "review_count": 156,
        "description": "Breathable mesh fabric. Quick-dry.",
        "attributes": {"category": "apparel", "type": "shirt"},
        "images": [
            "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
            "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800&q=80",
        ],
    },
    {
        "id": "ath_005",
        "title": "Athletic Wireless Earbuds",
        "price": "79.00",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": True,
        "rating": 4.0,
        "review_count": 61,
        "description": "Sweat-resistant earbuds for workouts. 6h battery.",
        "attributes": {"category": "electronics", "type": "earbuds"},
        "images": [
            "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80",
            "https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=800&q=80",
        ],
    },
    {
        "id": "ath_006",
        "title": "Premium Running Shoes",
        "price": "179.00",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": True,
        "rating": 4.6,
        "review_count": 320,
        "description": "Carbon-plate racing shoe. Premium materials, race-day fit.",
        "attributes": {"category": "running", "type": "shoes"},
        "images": [
            "https://images.unsplash.com/photo-1562183241-b937e95585b6?w=800&q=80",
            "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
        ],
    },
    {
        "id": "ath_007",
        "title": "Stability Running Shoes",
        "price": "159.00",
        "currency": "USD",
        "vendor": "Athletic Co",
        "available": True,
        "rating": 4.4,
        "review_count": 240,
        "description": "Medial post for overpronators. All-day comfort.",
        "attributes": {"category": "running", "type": "shoes"},
        "images": [
            "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80",
            "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80",
        ],
    },
]


AUDIO_HUB = [
    {
        "id": "aud_001",
        "title": "Demo Wireless Headphones",
        "price": "89.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.1,
        "review_count": 412,
        "description": "Entry-level over-ear wireless. 20h battery.",
        "attributes": {"category": "electronics", "type": "headphones"},
        "images": [
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
            "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800&q=80",
        ],
    },
    {
        "id": "aud_002",
        "title": "Noise-Cancelling Headphones",
        "price": "249.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.6,
        "review_count": 1820,
        "description": "Active noise cancelling. 30h battery. Bluetooth 5.3.",
        "attributes": {"category": "electronics", "type": "headphones"},
        "images": [
            "https://images.unsplash.com/photo-1576082712237-eb1335ce23a3?w=800&q=80",
            "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80",
        ],
    },
    {
        "id": "aud_003",
        "title": "Premium Studio Headphones",
        "price": "649.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.8,
        "review_count": 312,
        "description": "Reference-grade studio monitors. Wired + wireless.",
        "attributes": {"category": "electronics", "type": "headphones"},
        "images": [
            "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
            "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=800&q=80",
        ],
    },
    {
        "id": "aud_004",
        "title": "Wireless Earbuds Compact",
        "price": "129.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.4,
        "review_count": 740,
        "description": "Tiny case. ANC. Multi-device pairing.",
        "attributes": {"category": "electronics", "type": "earbuds"},
        "images": [
            "https://images.unsplash.com/photo-1756902368926-eb9e5e9d2a69?w=800&q=80",
            "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&q=80",
        ],
    },
    {
        "id": "aud_005",
        "title": "Bluetooth Speaker Mini",
        "price": "59.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.3,
        "review_count": 1102,
        "description": "Portable speaker. 12h battery. IPX7.",
        "attributes": {"category": "electronics", "type": "speaker"},
        "images": [
            "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
            "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
        ],
    },
    {
        "id": "aud_006",
        "title": "Studio Headphones Mid-Range",
        "price": "179.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.4,
        "review_count": 612,
        "description": "Over-ear, wired. Detachable cable. Studio-grade drivers.",
        "attributes": {"category": "electronics", "type": "headphones"},
        "images": [
            "https://images.unsplash.com/photo-1420161900862-9a86fa1f5c79?w=800&q=80",
            "https://images.unsplash.com/photo-1493723843671-1d655e66ac1c?w=800&q=80",
        ],
    },
    {
        "id": "aud_007",
        "title": "Sport Wireless Earbuds",
        "price": "99.00",
        "currency": "USD",
        "vendor": "Audio Hub",
        "available": True,
        "rating": 4.2,
        "review_count": 540,
        "description": "Sweat-resistant. Secure-fit ear hooks. 8h battery.",
        "attributes": {"category": "electronics", "type": "earbuds"},
        "images": [
            "https://images.unsplash.com/photo-1758521960921-7d5eab7cf50a?w=800&q=80",
            "https://images.unsplash.com/photo-1525825691042-e14d9042fc70?w=800&q=80",
        ],
    },
]


COFFEE_BAR = [
    {
        "id": "cof_001",
        "title": "Ceramic Coffee Mug",
        "price": "14.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.4,
        "review_count": 89,
        "description": "12oz ceramic mug. Dishwasher safe.",
        "attributes": {"category": "lifestyle", "type": "mug"},
        "images": [
            "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
            "https://images.unsplash.com/photo-1572119865084-43c285814d63?w=800&q=80",
        ],
    },
    {
        "id": "cof_002",
        "title": "Travel Coffee Tumbler",
        "price": "28.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.6,
        "review_count": 312,
        "description": "Vacuum-insulated 16oz. Keeps coffee hot 6h.",
        "attributes": {"category": "lifestyle", "type": "tumbler"},
        "images": [
            "https://images.unsplash.com/photo-1530138295342-c7c921529ee9?w=800&q=80",
            "https://images.unsplash.com/photo-1588793076577-4c2b666452d3?w=800&q=80",
        ],
    },
    {
        "id": "cof_003",
        "title": "Single-Origin Coffee Beans (Ethiopia)",
        "price": "18.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.7,
        "review_count": 624,
        "description": "Light roast Ethiopian Yirgacheffe. 12oz whole bean.",
        "attributes": {"category": "lifestyle", "type": "coffee"},
        "images": [
            "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
            "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
        ],
    },
    {
        "id": "cof_004",
        "title": "Pour-Over Coffee Set",
        "price": "42.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.5,
        "review_count": 178,
        "description": "Glass dripper + carafe. 2-cup capacity.",
        "attributes": {"category": "lifestyle", "type": "brewing"},
        "images": [
            "https://images.unsplash.com/photo-1541469406036-71229832e06e?w=800&q=80",
            "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
        ],
    },
    {
        "id": "cof_005",
        "title": "Decaf Coffee Beans",
        "price": "16.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.2,
        "review_count": 98,
        "description": "Swiss-water-process decaf. 12oz.",
        "attributes": {"category": "lifestyle", "type": "coffee"},
        "images": [
            "https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?w=800&q=80",
            "https://images.unsplash.com/photo-1753837787691-84a06d715d24?w=800&q=80",
        ],
    },
    {
        "id": "cof_006",
        "title": "Ceramic Coffee Mug (Large 16oz)",
        "price": "19.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.6,
        "review_count": 312,
        "description": "16oz wide-mouth ceramic mug. Microwave + dishwasher safe.",
        "attributes": {"category": "lifestyle", "type": "mug"},
        "images": [
            "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
            "https://images.unsplash.com/photo-1534040385115-33dcb3acba5b?w=800&q=80",
        ],
    },
    {
        "id": "cof_007",
        "title": "Stoneware Coffee Mug Set of 2",
        "price": "24.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.3,
        "review_count": 156,
        "description": "Set of two matching 12oz stoneware mugs. Hand-finished glaze.",
        "attributes": {"category": "lifestyle", "type": "mug"},
        "images": [
            "https://images.unsplash.com/photo-1520485521983-bfaa0bc6c80e?w=800&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        ],
    },
    {
        "id": "cof_008",
        "title": "Insulated Coffee Mug",
        "price": "22.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.5,
        "review_count": 198,
        "description": "Double-wall vacuum insulation. Keeps coffee hot for 4 hours.",
        "attributes": {"category": "lifestyle", "type": "mug"},
        "images": [
            "https://images.unsplash.com/photo-1604713055037-ef1ec567a47b?w=800&q=80",
            "https://images.unsplash.com/photo-1605539582747-ce302b9afca2?w=800&q=80",
        ],
    },
    {
        "id": "cof_009",
        "title": "Single-Origin Coffee Beans (Colombia)",
        "price": "17.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.5,
        "review_count": 412,
        "description": "Medium roast Colombian Huila. Notes of caramel and chocolate. 12oz.",
        "attributes": {"category": "lifestyle", "type": "coffee"},
        "images": [
            "https://images.unsplash.com/photo-1525088553748-01d6e210e00b?w=800&q=80",
            "https://images.unsplash.com/photo-1497515114629-f71d768fd07c?w=800&q=80",
        ],
    },
    {
        "id": "cof_010",
        "title": "Single-Origin Coffee Beans (Kenya)",
        "price": "19.00",
        "currency": "USD",
        "vendor": "Coffee Bar",
        "available": True,
        "rating": 4.6,
        "review_count": 287,
        "description": "Light-medium roast Kenya AA. Bright acidity, blackcurrant notes. 12oz.",
        "attributes": {"category": "lifestyle", "type": "coffee"},
        "images": [
            "https://images.unsplash.com/photo-1422207109431-97544339f995?w=800&q=80",
            "https://images.unsplash.com/photo-1459755486867-b55449bb39ff?w=800&q=80",
        ],
    },
]


MERCHANTS: dict[str, list[dict]] = {
    "athletic-co.myshopify.com": ATHLETIC_CO,
    "audio-hub.myshopify.com": AUDIO_HUB,
    "coffee-bar.myshopify.com": COFFEE_BAR,
}
